apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: staging
  labels:
    app: react-app
    managed-by: github-actions
spec:
  imagePullSecrets:
    - name: acr-secret
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: argocdacrjk.azurecr.io/react-cicd-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_ENV
              value: "production"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20